name: Postgres Language Server CLI Action
description: Setup Postgres Language Server on GitHub Actions runners
author: Supabase-Community
inputs:
  version:
    description: Semver-Version of CLI to install. Use "latest" for always using the latest stable release.
    required: true
outputs:
  installed-version:
    description: Version of the CLI installed on your runner.
runs:
  using: node20
  main: dist/index.js
