name: PGLT Cli Action
description: Setup PGLT on Github Actions Runners
author: Supabase-Community
inputs:
  version:
    description: Semver-Version of CLI to install. Use "latest" for always using the latest stable release.
    required: true
outputs:
  installed-version:
    description: Version that of the CLI that was installed on your runner.
runs:
  using: node20
  main: dist/index.js
