name: Verify Action Works

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: ${{ inputs.version }}
      - run: postgrestools check --skip-db test.sql
